let data = [
    {
        // _id: 1,
        name: "product-1",
        slug: "product-1",
        img: "/images/1.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "beauty",
        brand: "olay",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },
    {
        // _id: 1,
        name: "product-2",
        slug: "product-2",
        img: "/images/2.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "beauty",
        brand: "loreal",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },
    {
        // _id: 1,
        name: "product-3",
        slug: "product-3",
        img: "/images/3.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "beauty",
        brand: "olay",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },
    {
        // _id: 1,
        name: "product-4",
        slug: "product-4",
        img: "/images/4.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "fashion",
        brand: "olay",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },
    {
        // _id: 1,
        name: "product-5",
        slug: "product-5",
        img: "/images/5.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "fashion",
        brand: "olay",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },
    {
        // _id: 1,
        name: "product-6",
        slug: "product-6",
        img: "/images/6.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "fashion",
        brand: "olay",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },
    {
        // _id: 1,
        name: "product-7",
        slug: "product-7",
        img: "/images/7.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "fashion",
        brand: "olay",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },
    {
        // _id: 1,
        name: "product-8",
        slug: "product-8",
        img: "/images/8.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "beauty",
        brand: "olay",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },
    {
        // _id: 1,
        name: "product-9",
        slug: "product-9",
        img: "/images/9.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "beauty",
        brand: "olay",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },
    {
        // _id: 1,
        name: "product-10",
        slug: "product-10",
        img: "/images/10.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "electronics",
        brand: "olay",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },
    {
        // _id: 1,
        name: "product-11",
        slug: "product-11",
        img: "/images/11.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "beauty",
        brand: "olay",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },
    {
        // _id: 1,
        name: "product-12",
        slug: "product-12",
        img: "/images/12.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "electronics",
        brand: "olay",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },

    {
        // _id: 1,
        name: "product-1",
        slug: "product-1",
        img: "/images/1.jpg",
        price: "100",
        description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
        rating: "5",
        numberOfRating: "444",
        stoke: "10",
        category: "electronics",
        brand: "olay",
        coupon: 'raihan',
        discount: 50,
        discountLimit: 0,
        totalSell: 120
    },

]

export default data


// this was my previous data structure

// {
//     // _id: 1,
//     name: "product-1",
//     slug: "product-1",
//     img: "/images/1.jpg",
//     price: "100",
//     description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is.",
//     rating: "5",
//     numberOfRating: "444",
//     stoke: "10",
//     category: "beauty",
//     brand: "olay",
//     coupon: 'raihan',
//     discount: 50,
//     discountLimit: 0,
//     totalSell: 120
// },